SRC = ./ft_display_file.c

EXEC = ft_display_file

OBJC = ft_display_file.o

all:
	gcc -Wall -Wextra -Werror -c $(SRC)
	gcc -o $(EXEC) -Wall -Wextra -Werror $(OBJC)

clean:
	/bin/rm -r $(OBJC)

fclean:
	/bin/rm -rf $(EXEC) $(OBJC)
